name: doxygen-deploy

on:
  push:
    branches: [ master ] 
jobs:
  deploy-worksheet5:
    runs-on: ubuntu-latest

    steps:
  - name: Run doxygen
  run: |
    cd Worksheet5
    doxygen

- name: Deploy
  uses: JamesIves/github-pages-deploy-action@v4
  with:
    branch: gh-pages
    folder: Worksheet5/html

